#!/usr/bin/env bash
# Scaffold a new modules/<feature-name>/ folder with colocated Go + TS/React stubs.
#
# Usage:
#   .github/skills/new-feature-module/scripts/scaffold.sh <feature-name> [--ssr] [layers...]
#   .github/skills/new-feature-module/scripts/scaffold.sh -i
#
# Options:
#   -i, --interactive           Interactive mode — step-by-step prompts
#   --ssr                       Enable SSR for all page routes (non-interactive only)
#   --custom-ui <dir>           Path to custom UI template overrides (generated by generate-ui.sh)
#
# Layers (non-interactive):
#   h = handler    s = service    r = repository    m = model
#   p = page       f = frontend (React + esbuild)
#
# Must be run from the repo root.

set -euo pipefail

# ── Help ─────────────────────────────────────────────────────────
usage() {
  echo "Usage:" >&2
  echo "  scaffold.sh <feature-name> [--ssr] [layers...]" >&2
  echo "  scaffold.sh -i" >&2
  echo "" >&2
  echo "Options:" >&2
  echo "  --custom-ui <dir>   Path to custom UI template overrides" >&2
  echo "" >&2
  echo "Layers: h(handler) s(service) r(repo) m(model) p(page) f(frontend)" >&2
  echo "Default (no layers) = h s r m p f (fullstack)" >&2
  echo "" >&2
  echo "Interactive:  scaffold.sh -i" >&2
  exit 1
}

# ── Helpers ──────────────────────────────────────────────────────
prompt()     { local m="$1" d="$2"; read -r -p "$m [$d]: " v; echo "${v:-$d}"; }
prompt_yn()  { local m="$1" d="${2:-n}"; read -r -p "$m [y/N]: " v; v="${v:-$d}"; [[ "${v,,}" == "y" ]]; }
prompt_access() {
  local m="$1" d="${2:-same-origin}" v
  while true; do
    read -r -p "$m [public/private/same-origin] ($d): " v; v="${v:-$d}"
    case "$v" in public|private|same-origin) echo "$v"; return ;; esac
    echo "  Invalid: public/private/same-origin" >&2
  done
}

# ── Core state check ──────────────────────────────────────────────
check_core() {
  local f=".core-state.json"
  if [[ -f "$f" ]]; then
    local nc; nc=$(jq -r '.files | to_entries[] | select(.value.created == false) | .key' "$f" 2>/dev/null || echo "")
    [[ -n "$nc" ]] && { echo "⚠️  Core not initialized. Run init-core.sh first." >&2; exit 1; }
  elif [[ ! -d "core/router" ]]; then
    echo "⚠️  Core not found. Run init-core.sh first." >&2; exit 1
  fi
  return 0
}

# ── Parse args ──────────────────────────────────────────────────
INTERACTIVE=false; SSR=false; CUSTOM_UI_DIR=""; ARGS=()
while [[ $# -gt 0 ]]; do
  case "$1" in
    -i|--interactive) INTERACTIVE=true; shift ;;
    --ssr) SSR=true; shift ;;
    --custom-ui) CUSTOM_UI_DIR="$2"; shift 2 ;;
    --help|-h) usage ;;
    *) ARGS+=("$1"); shift ;;
  esac
done
set -- "${ARGS[@]}"

# ── Validate feature name before anything else ──────────
if ! $INTERACTIVE; then
  FEATURE="${1:-}"; [[ -z "$FEATURE" ]] && { echo "❌ Nama module wajib diisi. Contoh:" >&2; echo "  scaffold.sh blog                  # fullstack default" >&2; echo "  scaffold.sh blog --ssr           # dengan SSR" >&2; echo "  scaffold.sh blog --ssr h s r m   # backend only + SSR" >&2; echo "  scaffold.sh blog h p f           # frontend only" >&2; echo "  scaffold.sh --help               # bantuan lengkap" >&2; exit 0; }
  [[ ! "$FEATURE" =~ ^[a-z][a-z0-9-]*$ ]] && { echo "Error: kebab-case." >&2; exit 1; }
fi

check_core
[[ ! -d "modules" ]] && { echo "Error: run from repo root." >&2; exit 1; }

# ── Parse non-interactive args ──────────────────────────
if ! $INTERACTIVE; then
  [[ -d "modules/${FEATURE}" ]] && { echo "Error: modules/${FEATURE} sudah ada." >&2; exit 1; }
  shift || true
  LAYERS="${*:-h s r m p f}"
  # Non-interactive defaults
  ACC_PAGE="public"; ACC_DETAIL="public"
  ACC_CREATE="same-origin"; ACC_LIST="same-origin"; ACC_GET="same-origin"
  ACC_UPDATE="same-origin"; ACC_DELETE="same-origin"
  SSR_PAGE=$SSR; SSR_DETAIL=$SSR
  RL_CREATE="10"; RL_UPDATE="10"; RL_DELETE="10"
  echo "  Layers: $(echo $LAYERS | tr ' ' ',')  SSR: $SSR"
fi

# Validate custom-ui dir if provided
if [[ -n "$CUSTOM_UI_DIR" ]]; then
  if [[ ! -d "$CUSTOM_UI_DIR" ]]; then
    echo "Error: --custom-ui directory not found: ${CUSTOM_UI_DIR}" >&2
    exit 1
  fi
  echo "  Custom UI: ${CUSTOM_UI_DIR}"
fi

# ── Interactive Mode ────────────────────────────────────────────
if $INTERACTIVE; then
  echo ""; echo "╔════════════════════════════════════╗"
  echo "║  Flow — Interactive Scaffold       ║"; echo "╚════════════════════════════════════╝"; echo ""

  while true; do
    FEATURE=$(prompt "Step 1: Nama fitur (kebab-case)" "")
    [[ -z "$FEATURE" ]] && { echo "  Wajib diisi."; continue; }
    [[ ! "$FEATURE" =~ ^[a-z][a-z0-9-]*$ ]] && { echo "  Gunakan kebab-case."; continue; }
    [[ -d "modules/${FEATURE}" ]] && { echo "  modules/${FEATURE} sudah ada."; continue; }
    break
  done

  echo "Step 2: Layer (h s r m p f)"
  LAYERS=$(prompt "  Default semua layer" "h s r m p f")
  has() { local x; for x in $LAYERS; do [[ "$x" == "$1" ]] && return 0; done; return 1; }

  echo ""; echo "Step 3: Akses per endpoint"
  ACC_PAGE=$(prompt_access "  GET /${FEATURE}" "public")
  ACC_DETAIL=$(prompt_access "  GET /${FEATURE}/{id}" "public")
  ACC_CREATE=$(prompt_access "  POST /api/${FEATURE}" "same-origin")
  ACC_LIST=$(prompt_access "  GET /api/${FEATURE}" "same-origin")
  ACC_GET=$(prompt_access "  GET /api/${FEATURE}/{id}" "same-origin")
  ACC_UPDATE=$(prompt_access "  PUT /api/${FEATURE}/{id}" "same-origin")
  ACC_DELETE=$(prompt_access "  DELETE /api/${FEATURE}/{id}" "same-origin")

  echo ""; echo "Step 4: SSR per halaman"
  SSR_PAGE=false; SSR_DETAIL=false
  has "p" && { prompt_yn "  /${FEATURE} SSR?" && SSR_PAGE=true; prompt_yn "  /${FEATURE}/{id} SSR?" && SSR_DETAIL=true; }

  echo ""; echo "Step 5: Rate limit (req/s, Enter=10)"
  RL_CREATE=$(prompt "  POST /api/${FEATURE}" "10")
  RL_UPDATE=$(prompt "  PUT /api/${FEATURE}/{id}" "10")
  RL_DELETE=$(prompt "  DELETE /api/${FEATURE}/{id}" "10")

  echo ""; echo "=== RINGKASAN ==="
  echo "Feature: $FEATURE | Layers: $LAYERS"
  echo "  GET  /${FEATURE}          ($ACC_PAGE${SSR_PAGE:+", SSR"})"
  echo "  GET  /${FEATURE}/{id}     ($ACC_DETAIL${SSR_DETAIL:+", SSR"})"
  echo "  POST /api/${FEATURE}      ($ACC_CREATE, ${RL_CREATE}/s)"
  echo "  GET  /api/${FEATURE}      ($ACC_LIST)"
  echo "  GET  /api/${FEATURE}/{id} ($ACC_GET)"
  echo "  PUT  /api/${FEATURE}/{id} ($ACC_UPDATE, ${RL_UPDATE}/s)"
  echo "  DEL  /api/${FEATURE}/{id} ($ACC_DELETE, ${RL_DELETE}/s)"
  prompt_yn "Lanjutkan?" "y" || { echo "Dibatalkan."; exit 0; }
fi

# ── Custom UI render helper ──────────────────────────────────────
# render() checks custom-ui dir first, falls back to skill default

render() {
  local src="$1" dst="$2"
  local src_path=""

  # Check custom-ui override first
  if [[ -n "$CUSTOM_UI_DIR" && -f "${CUSTOM_UI_DIR}/${src}" ]]; then
    src_path="${CUSTOM_UI_DIR}/${src}"
  else
    src_path="${SDIR}/${src}"
  fi

  sed \
    -e "s/__PACKAGE__/${PKG}/g" \
    -e "s/__FEATURE_TITLE__/${FTITLE}/g" \
    -e "s/__FEATURE__/${FEATURE}/g" \
    -e "s/__SSR_PAGE__/${SSR_PAGE}/g" \
    -e "s/__SSR_DETAIL__/${SSR_DETAIL}/g" \
    -e "s/__ACC_PAGE__/${ACC_PAGE_GO}/g" \
    -e "s/__ACC_DETAIL__/${ACC_DETAIL_GO}/g" \
    -e "s/__ACC_CREATE__/${ACC_CREATE_GO}/g" \
    -e "s/__ACC_LIST__/${ACC_LIST_GO}/g" \
    -e "s/__ACC_GET__/${ACC_GET_GO}/g" \
    -e "s/__ACC_UPDATE__/${ACC_UPDATE_GO}/g" \
    -e "s/__ACC_DELETE__/${ACC_DELETE_GO}/g" \
    -e "s/__RL_CREATE__/${RL_CREATE_SED}/g" \
    -e "s/__RL_UPDATE__/${RL_UPDATE_SED}/g" \
    -e "s/__RL_DELETE__/${RL_DELETE_SED}/g" \
    "${src_path}" > "${dst}"

  # Post-patch rate limit markers with actual Go expressions
  rl_expr() {
    local v="$1"
    if [[ -n "$v" && "$v" != "0" ]]; then
      echo "\\&router.RateLimitConfig{RequestsPerSecond: $v}"
    else
      echo "nil"
    fi
  }
  case "$(uname)" in
    Darwin) sed -i '' "s/${RL_CREATE_SED}/$(rl_expr "$RL_CREATE")/g; s/${RL_UPDATE_SED}/$(rl_expr "$RL_UPDATE")/g; s/${RL_DELETE_SED}/$(rl_expr "$RL_DELETE")/g" "$dst" ;;
    *) sed -i "s/${RL_CREATE_SED}/$(rl_expr "$RL_CREATE")/g; s/${RL_UPDATE_SED}/$(rl_expr "$RL_UPDATE")/g; s/${RL_DELETE_SED}/$(rl_expr "$RL_DELETE")/g" "$dst" ;;
  esac
}

# ── Common Setup ─────────────────────────────────────────────────
SDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/.."
TDIR="modules/${FEATURE}"
PKG="$(echo "$FEATURE" | tr -d '-')"
FTITLE="$(echo "$FEATURE" | awk -F'-' '{ for (i=1; i<=NF; i++) $i=toupper(substr($i,1,1)) substr($i,2); print }' OFS='')"

# Define has() if not in interactive mode (interactive mode already defines it)
if ! $INTERACTIVE; then
  has() { local x; for x in $LAYERS; do [[ "$x" == "$1" ]] && return 0; done; return 1; }
fi

mkdir -p "$TDIR"
has "f" && mkdir -p "$TDIR/components"
has "p" && mkdir -p "$TDIR/templates"

# Build Go expressions for access and rate limit
map_access() {
  case "$1" in
    public) echo "router.AccessPublic" ;;
    private) echo "router.AccessPrivate" ;;
    same-origin) echo "router.AccessSameOrigin" ;;
    *) echo "router.AccessSameOrigin" ;;
  esac
}
ACC_PAGE_GO=$(map_access "$ACC_PAGE")
ACC_DETAIL_GO=$(map_access "$ACC_DETAIL")
ACC_CREATE_GO=$(map_access "$ACC_CREATE")
ACC_LIST_GO=$(map_access "$ACC_LIST")
ACC_GET_GO=$(map_access "$ACC_GET")
ACC_UPDATE_GO=$(map_access "$ACC_UPDATE")
ACC_DELETE_GO=$(map_access "$ACC_DELETE")

# Rate limit markers (sed-friendly)
RL_CREATE_SED="REPLACERLCREATE"
RL_UPDATE_SED="REPLACERLUPDATE"
RL_DELETE_SED="REPLACERLDELETE"

# ── Generate ─────────────────────────────────────────────────────
render "module.go.tmpl" "$TDIR/module.go"

if has "p" || has "f"; then
  render "router.go.tmpl" "$TDIR/router.go"
else
  render "router.api.tmpl" "$TDIR/router.go"
fi

has "h" && {
  if has "p" || has "f"; then render "handler.go.tmpl" "$TDIR/handler.go"; else render "handler.api.tmpl" "$TDIR/handler.go"; fi
  render "handler_test.go.tmpl" "$TDIR/handler_test.go"
}
has "s" && { render "service.go.tmpl" "$TDIR/service.go"; render "service_test.go.tmpl" "$TDIR/service_test.go"; }
has "r" && render "repository.go.tmpl" "$TDIR/repository.go"
has "m" && render "model.go.tmpl" "$TDIR/model.go"

HAS_FE=false
has "p" && {
  render "shell.html.tmpl" "$TDIR/templates/shell.html"
  # Cek detail template dari custom-ui dulu, baru fallback ke skill default
  if [[ -n "$CUSTOM_UI_DIR" && -f "${CUSTOM_UI_DIR}/templates/detail.html.tmpl" ]]; then
    render "templates/detail.html.tmpl" "$TDIR/templates/detail.html"
  elif [[ -f "${SDIR}/templates/detail.html.tmpl" ]]; then
    render "templates/detail.html.tmpl" "$TDIR/templates/detail.html"
  fi
  # Copy skeleton templates for SSR (rendered by Go server)
  if [[ -f "${SDIR}/templates/skeleton-list.html.tmpl" ]]; then
    cp "${SDIR}/templates/skeleton-list.html.tmpl" "$TDIR/templates/skeleton-list.html"
    sed -i "s/__FEATURE__/${FEATURE}/g" "$TDIR/templates/skeleton-list.html"
  fi
  if [[ -f "${SDIR}/templates/skeleton-detail.html.tmpl" ]]; then
    cp "${SDIR}/templates/skeleton-detail.html.tmpl" "$TDIR/templates/skeleton-detail.html"
    sed -i "s/__FEATURE__/${FEATURE}/g" "$TDIR/templates/skeleton-detail.html"
  fi
}
has "f" && {
  HAS_FE=true
  render "Feature.tsx.tmpl"   "$TDIR/${FTITLE}.tsx"
  render "api.ts.tmpl"        "$TDIR/api.ts"
  render "esbuild.mjs.tmpl"   "$TDIR/esbuild.mjs"
  render "package.json.tmpl"  "$TDIR/package.json"
  render "api.test.ts.tmpl"      "$TDIR/api.test.ts"
  render "Feature.test.tsx.tmpl" "$TDIR/${FTITLE}.test.tsx"
  touch "$TDIR/components/.gitkeep"
}

# ── Register ─────────────────────────────────────────────────────
REG="modules/register.go"
IMPORT="_ \"github.com/ynwd/flow/modules/${FEATURE}\""
if grep -q "$IMPORT" "$REG" 2>/dev/null; then
  echo "  ✓ ${FEATURE} already registered"
elif [[ -f "$REG" ]] && grep -q "import (" "$REG"; then
  sed -i "/^)/i\\\t$IMPORT" "$REG"
  echo "  ✓ Registered ${FEATURE}"
else
  echo -e "package modules\n\nimport (\n\t$IMPORT\n)" > "$REG"
  echo "  ✓ Created register.go with ${FEATURE}"
fi

# ── Workspaces & build ───────────────────────────────────────────
if $HAS_FE; then
  node -e "
const p=require('./package.json');
if(!p.workspaces.includes('modules/${FEATURE}')) p.workspaces.push('modules/${FEATURE}');
require('fs').writeFileSync('./package.json', JSON.stringify(p,null,2)+'\n');
" 2>/dev/null || true
  echo "  ✓ Updated package.json"
  npm install --silent 2>&1 | tail -1
  npm run build -w "modules/${FEATURE}" 2>&1
else
  echo "  (skipped npm — no frontend)"
fi

echo ""; echo "─── All done ───"
echo "  go test ./modules/${FEATURE}/...     # backend tests"
echo "  go run .           # → localhost:3000/${FEATURE}"
